data:
  # 1 读mmap数据，2 读wal文件,配置目录, 3 读socket
  type: 1
  mmap: /home/work/sys/develop/feeder_huatai_insight/data/feed.stock.mem
  #mmap: ../data/qts;../data/159919
  wal_file: /home/work/sys/develop/feeder_huatai_insight_v_1.0/data
  feed_gateway: tcp://127.0.0.1:8000
  # 指定日期, 或设置为0  20250214
  sub_date: 0

dolphindb:
 #host: 192.168.101.237
  host: 192.168.71.101
  port: 8848
  userId: admin
  password: .123456
  dbpath: dfs://quota
  tradeknockname: TradeKnockTable
  tickname: qtick
  ordername: qorder
  knockname: qknock
  etfiopvname: qetfiopv




