data:
  # 1 读mmap数据，2 读wal文件, 3 读socket
  type: 3
  #  mmap: /home/work/sys/develop/feeder_ctp/data
  # mmap: /home/work/sys/develop/feeder_ctp/data;/home/work/sys/develop/feeder_huatai_insight/data
  mmap: /home/work/sys/develop/feeder_huatai_insight/data
  wal_file: /home/work/sys/develop/write_dolphindb/data/feed_20230425_20230425105537700.stock1.wal
  feed_gateway: tcp://127.0.0.1:8000

dolphindb:
  host: 192.168.101.237
  port: 8848
  userId: admin
  password: .123456
  dbpath: dfs://SAMPLE_TRDDB
  tradeknockname: TradeKnockTable
  tickname: QTickTable
  ordername: QOrderTable
  knockname: QKnockTable




